### ISSUE TITLE
Failure to render snapshots

### ISSUE THREAD

**Issue by mrlad** [AGoliath/wingview#1]
Importing all of our snapshots generate this error

_Your Snapshot file parsed ok but did not render correctly._

**Comment by AGoliath** [comment]
Thank you, could you attach (or DM on the forum) me a sample snapshot to I can have a look? I´ve never had a snapshot triggering that specific error before. 
Did you get the "not a wing 1.3.1" error before?

**Comment by mrlad** [comment]
This is the first time I've used the visualizer so no previous error messages.

The snapshot is too big to send via PM on the forums.  Would prefer not to upload the snapshot to a public forum.  Can I email it?

**Comment by AGoliath** [comment]
of course! you can mail it to _nameoftherepository_ -at-  mails.ac

**Comment by mrlad** [comment]
Sent a couple snapshots to your email.

**Comment by AGoliath** [comment]
Thanks! That was an easy fix/stupid mistake on my side. Version on the website is updated, your snaps render fine now.

**Comment by mrlad** [comment]
I'm still seeing the error even after loading the web page.

**Comment by AGoliath** [comment]
maybe you need to force-reload? (keep shift pressed and click on the refresh button in your browser).
it should say "Last Update: 31.07.2024"

**Comment by mrlad** [comment]
I cleared the cache and it worked.

**Comment by mrlad** [comment]
Confirmed fixed.
